//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaEvento
    {
        public int IdAgendaEvento { get; set; }
        public Nullable<System.DateTime> DataIni { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string Descricao { get; set; }
        public Nullable<byte> TipoEvento { get; set; }
        public string DiaSemana { get; set; }
        public Nullable<System.DateTime> HoraIni { get; set; }
        public Nullable<System.DateTime> HoraFim { get; set; }
        public Nullable<int> IdDocente { get; set; }
    
        public virtual Docente Docente { get; set; }
    }
}
