//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public Ambiente()
        {
            this.AgendaAmbiente = new HashSet<AgendaAmbiente>();
            this.Agendamento = new HashSet<Agendamento>();
            this.RecursoAmbiente = new HashSet<RecursoAmbiente>();
        }
    
        public int IdAmbiente { get; set; }
        public Nullable<int> IdLoc { get; set; }
        public Nullable<int> IdTipoAmbiente { get; set; }
        public Nullable<int> IdAgendaComponente { get; set; }
        public Nullable<short> Capac { get; set; }
        public string Nome { get; set; }
        public Nullable<short> Status { get; set; }
        public string Observacao { get; set; }
    
        public virtual ICollection<AgendaAmbiente> AgendaAmbiente { get; set; }
        public virtual AgendaComponente AgendaComponente { get; set; }
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual LocalAmbiente LocalAmbiente { get; set; }
        public virtual TipoAmbiente TipoAmbiente { get; set; }
        public virtual ICollection<RecursoAmbiente> RecursoAmbiente { get; set; }
    }
}
