//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaAtuacao
    {
        public AreaAtuacao()
        {
            this.Matriz = new HashSet<Matriz>();
            this.Docente = new HashSet<Docente>();
            this.Usuario = new HashSet<Usuario>();
            this.Componente = new HashSet<Componente>();
        }
    
        public int IdAreaAtuacao { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Matriz> Matriz { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Componente> Componente { get; set; }
    }
}
