//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioCivil
    {
        public int IdCalendarioCivil { get; set; }
        public System.DateTime DataInicial { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public int IdLegenda { get; set; }
        public string Descricao { get; set; }
    
        public virtual CalendarioLegenda CalendarioLegenda { get; set; }
    }
}
