//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMaterial
    {
        public CatMaterial()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int IdCategoriaMaterial { get; set; }
        public string NomeCat { get; set; }
    
        public virtual ICollection<Material> Material { get; set; }
    }
}
