//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatServico
    {
        public CatServico()
        {
            this.Servico = new HashSet<Servico>();
        }
    
        public int IdCategoriaServico { get; set; }
        public string NomeCatServico { get; set; }
    
        public virtual ICollection<Servico> Servico { get; set; }
    }
}
