//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR
    {
        public CR()
        {
            this.Turma = new HashSet<Turma>();
            this.Unidade = new HashSet<Unidade>();
        }
    
        public int IdCR { get; set; }
        public Nullable<int> IdModalidade { get; set; }
        public string Nome { get; set; }
        public string Codigo { get; set; }
    
        public virtual Modalidade Modalidade { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<Unidade> Unidade { get; set; }
    }
}
