//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int Id { get; set; }
        public Nullable<int> IdUnidade { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<int> IdCr { get; set; }
        public Nullable<int> IdMatriz { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<short> QtdeVagas { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> TipoOferta { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> Evento { get; set; }
    }
}
