//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Docente = new HashSet<Docente>();
        }
    
        public int IdEmpresa { get; set; }
        public Nullable<int> IdAgendaComponente { get; set; }
        public string NomeFantasia { get; set; }
        public string CNPJ { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Contato { get; set; }
    
        public virtual AgendaComponente AgendaComponente { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
    }
}
