//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriz
    {
        public Matriz()
        {
            this.Turma = new HashSet<Turma>();
            this.Modulo = new HashSet<Modulo>();
            this.ReprovacaoMatriz = new HashSet<ReprovacaoMatriz>();
            this.Material = new HashSet<Material>();
            this.Servico = new HashSet<Servico>();
        }
    
        public int IdMatriz { get; set; }
        public Nullable<int> IdModalidade { get; set; }
        public Nullable<int> IdAreaAtuacao { get; set; }
        public Nullable<int> IdCBO { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public string Nome { get; set; }
        public Nullable<int> CH { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> Aprovado { get; set; }
        public Nullable<int> IdResponsavel { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
    
        public virtual AreaAtuacao AreaAtuacao { get; set; }
        public virtual CBO CBO { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual Modalidade Modalidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Modulo> Modulo { get; set; }
        public virtual ICollection<ReprovacaoMatriz> ReprovacaoMatriz { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Servico> Servico { get; set; }
    }
}
