//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modalidade
    {
        public Modalidade()
        {
            this.CR = new HashSet<CR>();
            this.Matriz = new HashSet<Matriz>();
            this.Unidade = new HashSet<Unidade>();
        }
    
        public int IdModalidade { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<CR> CR { get; set; }
        public virtual ICollection<Matriz> Matriz { get; set; }
        public virtual ICollection<Unidade> Unidade { get; set; }
    }
}
