//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.AgendaAmbiente = new HashSet<AgendaAmbiente>();
            this.AgendaComponente = new HashSet<AgendaComponente>();
            this.AgendaDocente = new HashSet<AgendaDocente>();
            this.Componente = new HashSet<Componente>();
        }
    
        public int IdModulo { get; set; }
        public int IdMatriz { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<AgendaAmbiente> AgendaAmbiente { get; set; }
        public virtual ICollection<AgendaComponente> AgendaComponente { get; set; }
        public virtual ICollection<AgendaDocente> AgendaDocente { get; set; }
        public virtual Matriz Matriz { get; set; }
        public virtual ICollection<Componente> Componente { get; set; }
    }
}
