//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.RecursoAmbiente = new HashSet<RecursoAmbiente>();
        }
    
        public int idRecurso { get; set; }
        public int idTipoRecurso { get; set; }
        public string Descr { get; set; }
    
        public virtual TipoRecurso TipoRecurso { get; set; }
        public virtual ICollection<RecursoAmbiente> RecursoAmbiente { get; set; }
    }
}
