//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursoAmbiente
    {
        public int IdRecursoAmbiente { get; set; }
        public Nullable<int> IdRecurso { get; set; }
        public Nullable<int> IdAmbiente { get; set; }
        public short Status { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
