//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReprovacaoTurma
    {
        public int IdReprovacaoTurma { get; set; }
        public Nullable<int> IdTurma { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual Turma Turma { get; set; }
    }
}
