//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPEDomain : DbContext
    {
        //public SPEDomain()
        //    : base("name=SPEDomain")
        //{
        //}

        public SPEDomain()
            : base("SPEContext")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgendaAmbiente> AgendaAmbiente { get; set; }
        public DbSet<AgendaComponente> AgendaComponente { get; set; }
        public DbSet<AgendaDocente> AgendaDocente { get; set; }
        public DbSet<Ambiente> Ambiente { get; set; }
        public DbSet<AreaAtuacao> AreaAtuacao { get; set; }
        public DbSet<Calendario> Calendario { get; set; }
        public DbSet<CatMaterial> CatMaterial { get; set; }
        public DbSet<CatServico> CatServico { get; set; }
        public DbSet<CatUsuario> CatUsuario { get; set; }
        public DbSet<CBO> CBO { get; set; }
        public DbSet<Competencia> Competencia { get; set; }
        public DbSet<CompetenciaDocente> CompetenciaDocente { get; set; }
        public DbSet<CompetenciaEmpresa> CompetenciaEmpresa { get; set; }
        public DbSet<Componente> Componente { get; set; }
        public DbSet<ComponenteTipoAmbiente> ComponenteTipoAmbiente { get; set; }
        public DbSet<CR> CR { get; set; }
        public DbSet<CrUnidade> CrUnidade { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<CursoMaterial> CursoMaterial { get; set; }
        public DbSet<CursoServico> CursoServico { get; set; }
        public DbSet<Docente> Docente { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<LocalAmbiente> LocalAmbiente { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Matriz> Matriz { get; set; }
        public DbSet<MatrizComponente> MatrizComponente { get; set; }
        public DbSet<MatrizMaterial> MatrizMaterial { get; set; }
        public DbSet<MatrizServico> MatrizServico { get; set; }
        public DbSet<Modalidade> Modalidade { get; set; }
        public DbSet<ModalidadeUnidade> ModalidadeUnidade { get; set; }
        public DbSet<OrientadorArea> OrientadorArea { get; set; }
        public DbSet<RecursoAmbiente> RecursoAmbiente { get; set; }
        public DbSet<Servico> Servico { get; set; }
        public DbSet<TipoAmbiente> TipoAmbiente { get; set; }
        public DbSet<TipoAtividade> TipoAtividade { get; set; }
        public DbSet<TipoContrato> TipoContrato { get; set; }
        public DbSet<Turno> Turno { get; set; }
        public DbSet<UnCurricular> UnCurricular { get; set; }
        public DbSet<Unidade> Unidade { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
