//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAtividade
    {
        public TipoAtividade()
        {
            this.AgendaDocente = new HashSet<AgendaDocente>();
        }
    
        public int IdTipoAtividade { get; set; }
        public string Nome { get; set; }
        public bool Interna { get; set; }
    
        public virtual ICollection<AgendaDocente> AgendaDocente { get; set; }
    }
}
