//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turma
    {
        public Turma()
        {
            this.AgendaAmbiente = new HashSet<AgendaAmbiente>();
            this.AgendaComponente = new HashSet<AgendaComponente>();
            this.AgendaDocente = new HashSet<AgendaDocente>();
            this.Agendamento = new HashSet<Agendamento>();
            this.ReprovacaoTurma = new HashSet<ReprovacaoTurma>();
            this.Material = new HashSet<Material>();
            this.Servico = new HashSet<Servico>();
        }
    
        public int IdTurma { get; set; }
        public Nullable<int> IdUnidade { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<int> IdCR { get; set; }
        public Nullable<int> IdMatriz { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<short> QtdeVagas { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> TipoOferta { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> Evento { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<int> Aprovado { get; set; }
        public Nullable<int> IdResponsavel { get; set; }
    
        public virtual ICollection<AgendaAmbiente> AgendaAmbiente { get; set; }
        public virtual ICollection<AgendaComponente> AgendaComponente { get; set; }
        public virtual ICollection<AgendaDocente> AgendaDocente { get; set; }
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual CR CR { get; set; }
        public virtual Matriz Matriz { get; set; }
        public virtual ICollection<ReprovacaoTurma> ReprovacaoTurma { get; set; }
        public virtual Turno Turno { get; set; }
        public virtual Unidade Unidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Servico> Servico { get; set; }
    }
}
