//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public Turno()
        {
            this.Turma = new HashSet<Turma>();
        }
    
        public int IdTurno { get; set; }
        public string Descr { get; set; }
        public Nullable<System.TimeSpan> HoraIni { get; set; }
        public Nullable<System.TimeSpan> HoraFim { get; set; }
    
        public virtual ICollection<Turma> Turma { get; set; }
    }
}
