//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senai.SPE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidade
    {
        public Unidade()
        {
            this.AgendaComponente = new HashSet<AgendaComponente>();
            this.Turma = new HashSet<Turma>();
            this.CR = new HashSet<CR>();
            this.Modalidade = new HashSet<Modalidade>();
        }
    
        public int IdUnidade { get; set; }
        public string Descr { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> Codigo { get; set; }
    
        public virtual ICollection<AgendaComponente> AgendaComponente { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<CR> CR { get; set; }
        public virtual ICollection<Modalidade> Modalidade { get; set; }
    }
}
